import { ShowType } from '@/types/showType';

// 추후 삭제 예정
export const data: ShowType[] = [
  {
    id: '1',
    title: '맨 오브 라만차',
    place_name: '광림아트센터 BBH홀',
    img_source: '/images/a1.jpg',
    running_time_minute: 120,
    min_age: 16,
    start_date: '2025.05.01',
    end_date: '2025.07.13',
    category: '',
    intermission_time: 15,
    ticket_date_time: 120,
  },
  {
    id: '2',
    title: '엘리자벳',
    place_name: '광림아트센터 BBH홀',
    img_source: '/images/a2.jpg',
    running_time_minute: 120,
    min_age: 16,
    start_date: '2025.05.01',
    end_date: '2025.07.13',
    category: '',
    intermission_time: 15,
    ticket_date_time: 120,
  },
  {
    id: '3',
    title: '시지프스3',
    place_name: '광림아트센터 BBH홀',
    img_source: '/images/a3.jpg',
    running_time_minute: 120,
    min_age: 16,
    start_date: '2025.05.01',
    end_date: '2025.07.13',
    category: '',
    intermission_time: 15,
    ticket_date_time: 120,
  },
  {
    id: '4',
    title: '시지프스4',
    place_name: '광림아트센터 BBH홀',
    img_source: '/images/a3.jpg',
    running_time_minute: 120,
    min_age: 16,
    start_date: '2025.05.01',
    end_date: '2025.07.13',
    category: '',
    intermission_time: 15,
    ticket_date_time: 120,
  },
  {
    id: '5',
    title: '시지프스5',
    place_name: '광림아트센터 BBH홀',
    img_source: '/images/a3.jpg',
    running_time_minute: 120,
    min_age: 16,
    start_date: '2025.05.01',
    end_date: '2025.07.13',
    category: '',
    intermission_time: 15,
    ticket_date_time: 120,
  },
  {
    id: '6',
    title: '시지프스6',
    place_name: '광림아트센터 BBH홀',
    img_source: '/images/a3.jpg',
    running_time_minute: 120,
    min_age: 16,
    start_date: '2025.05.01',
    end_date: '2025.07.13',
    category: '',
    intermission_time: 15,
    ticket_date_time: 120,
  },
];

export const dummyData = {
  code: '200',
  message: '성공',
  data: data,
};
