export interface SeatsType {
  id: string;
  row: number;
  column: number;
  status: 'disabled' | 'book' | 'available';
}
export interface ZoneType {
  zoneId: string;
  zoneName: string;
  seats: SeatsType[];
}
export const bookingDummyData: ZoneType[] = [
  {
    zoneId: 'A',
    zoneName: 'A',
    seats: [
      { id: 'A-1', row: 1, column: 1, status: 'disabled' },
      { id: 'A-2', row: 1, column: 2, status: 'disabled' },
      { id: 'A-3', row: 1, column: 3, status: 'available' },
      { id: 'A-4', row: 1, column: 4, status: 'available' },
      { id: 'A-5', row: 1, column: 5, status: 'book' },
      { id: 'A-6', row: 1, column: 6, status: 'book' },
      { id: 'A-7', row: 1, column: 7, status: 'book' },
      { id: 'A-8', row: 1, column: 8, status: 'book' },
      { id: 'A-9', row: 1, column: 9, status: 'available' },
      { id: 'A-10', row: 1, column: 10, status: 'available' },
      { id: 'A-11', row: 1, column: 11, status: 'available' },
      { id: 'A-12', row: 1, column: 12, status: 'available' },
      { id: 'A-13', row: 1, column: 13, status: 'available' },
      { id: 'A-14', row: 1, column: 14, status: 'available' },
      { id: 'A-15', row: 1, column: 15, status: 'available' },
      { id: 'A-16', row: 1, column: 16, status: 'available' },
      { id: 'A-17', row: 1, column: 17, status: 'available' },
      { id: 'A-18', row: 1, column: 18, status: 'available' },
      { id: 'A-19', row: 1, column: 19, status: 'disabled' },
      { id: 'A-20', row: 1, column: 20, status: 'disabled' },
      { id: 'A-21', row: 2, column: 1, status: 'available' },
      { id: 'A-22', row: 2, column: 2, status: 'available' },
      { id: 'A-23', row: 2, column: 3, status: 'available' },
      { id: 'A-24', row: 2, column: 4, status: 'available' },
      { id: 'A-25', row: 2, column: 5, status: 'available' },
      { id: 'A-26', row: 2, column: 6, status: 'available' },
      { id: 'A-27', row: 2, column: 7, status: 'available' },
      { id: 'A-28', row: 2, column: 8, status: 'available' },
      { id: 'A-29', row: 2, column: 9, status: 'available' },
      { id: 'A-30', row: 2, column: 10, status: 'available' },
      { id: 'A-31', row: 2, column: 11, status: 'available' },
      { id: 'A-32', row: 2, column: 12, status: 'available' },
      { id: 'A-33', row: 2, column: 13, status: 'available' },
      { id: 'A-34', row: 2, column: 14, status: 'available' },
      { id: 'A-35', row: 2, column: 15, status: 'book' },
      { id: 'A-36', row: 2, column: 16, status: 'book' },
      { id: 'A-37', row: 2, column: 17, status: 'book' },
      { id: 'A-38', row: 2, column: 18, status: 'book' },
      { id: 'A-39', row: 2, column: 19, status: 'book' },
      { id: 'A-40', row: 2, column: 20, status: 'book' },
      { id: 'A-21a', row: 3, column: 1, status: 'available' },
      { id: 'A-22a', row: 3, column: 2, status: 'available' },
      { id: 'A-23a', row: 3, column: 3, status: 'available' },
      { id: 'A-24a', row: 3, column: 4, status: 'available' },
      { id: 'A-25a', row: 3, column: 5, status: 'available' },
      { id: 'A-26a', row: 3, column: 6, status: 'available' },
      { id: 'A-27a', row: 3, column: 7, status: 'available' },
      { id: 'A-28a', row: 3, column: 8, status: 'available' },
      { id: 'A-29a', row: 3, column: 9, status: 'available' },
      { id: 'A-30a', row: 3, column: 10, status: 'available' },
      { id: 'A-31a', row: 3, column: 11, status: 'available' },
      { id: 'A-32a', row: 3, column: 12, status: 'available' },
      { id: 'A-33a', row: 3, column: 13, status: 'available' },
      { id: 'A-34a', row: 3, column: 14, status: 'available' },
      { id: 'A-35a', row: 3, column: 15, status: 'available' },
      { id: 'A-36a', row: 3, column: 16, status: 'available' },
      { id: 'A-37a', row: 3, column: 17, status: 'available' },
      { id: 'A-38a', row: 3, column: 18, status: 'available' },
      { id: 'A-39a', row: 3, column: 19, status: 'available' },
      { id: 'A-40a', row: 3, column: 20, status: 'available' },
      { id: 'A-20ab', row: 4, column: 20, status: 'available' },
      { id: 'A-21ab', row: 4, column: 1, status: 'available' },
      { id: 'A-22ab', row: 4, column: 2, status: 'available' },
      { id: 'A-23ab', row: 4, column: 3, status: 'available' },
      { id: 'A-24ab', row: 4, column: 4, status: 'available' },
      { id: 'A-25ab', row: 4, column: 5, status: 'available' },
      { id: 'A-26ab', row: 4, column: 6, status: 'available' },
      { id: 'A-27ab', row: 4, column: 7, status: 'available' },
      { id: 'A-28ab', row: 4, column: 8, status: 'available' },
      { id: 'A-29bc', row: 4, column: 9, status: 'available' },
      { id: 'A-30bc', row: 4, column: 10, status: 'available' },
      { id: 'A-31bc', row: 4, column: 11, status: 'available' },
      { id: 'A-32bc', row: 4, column: 12, status: 'available' },
      { id: 'A-33bc', row: 4, column: 13, status: 'available' },
      { id: 'A-34bc', row: 4, column: 14, status: 'available' },
      { id: 'A-35bc', row: 4, column: 15, status: 'available' },
      { id: 'A-36bc', row: 4, column: 16, status: 'available' },
      { id: 'A-37bc', row: 4, column: 17, status: 'available' },
      { id: 'A-38bc', row: 4, column: 18, status: 'available' },
    ],
  },
  {
    zoneId: 'B',
    zoneName: 'B',
    seats: [
      { id: 'B-1', row: 1, column: 1, status: 'available' },
      { id: 'B-2', row: 1, column: 2, status: 'available' },
      { id: 'B-3', row: 1, column: 3, status: 'available' },
      { id: 'B-4', row: 1, column: 4, status: 'available' },
      { id: 'B-5', row: 1, column: 5, status: 'available' },
      { id: 'B-6', row: 1, column: 6, status: 'available' },
      { id: 'B-7', row: 1, column: 7, status: 'available' },
      { id: 'B-8', row: 1, column: 8, status: 'available' },
      { id: 'B-9', row: 1, column: 9, status: 'available' },
      { id: 'B-10', row: 1, column: 10, status: 'available' },
      { id: 'B-11', row: 2, column: 1, status: 'available' },
      { id: 'B-12', row: 2, column: 2, status: 'available' },
      { id: 'B-13', row: 2, column: 3, status: 'available' },
      { id: 'B-14', row: 2, column: 4, status: 'available' },
      { id: 'B-15', row: 2, column: 5, status: 'available' },
      { id: 'B-16', row: 2, column: 6, status: 'available' },
      { id: 'B-17', row: 2, column: 7, status: 'available' },
      { id: 'B-18', row: 2, column: 8, status: 'available' },
      { id: 'B-19', row: 2, column: 9, status: 'available' },
      { id: 'B-20', row: 2, column: 10, status: 'available' },
    ],
  },
  {
    zoneId: 'C',
    zoneName: 'C',
    seats: [
      { id: 'C-1', row: 1, column: 1, status: 'available' },
      { id: 'C-2', row: 1, column: 2, status: 'disabled' },
      { id: 'C-3', row: 1, column: 3, status: 'disabled' },
      { id: 'C-4', row: 1, column: 4, status: 'available' },
      { id: 'C-5', row: 1, column: 5, status: 'available' },
      { id: 'C-6', row: 1, column: 6, status: 'available' },
      { id: 'C-7', row: 1, column: 7, status: 'available' },
      { id: 'C-8', row: 1, column: 8, status: 'available' },
      { id: 'C-9', row: 1, column: 9, status: 'available' },
      { id: 'C-10', row: 1, column: 10, status: 'available' },
      { id: 'C-11', row: 2, column: 1, status: 'available' },
      { id: 'C-12', row: 2, column: 2, status: 'available' },
      { id: 'C-13', row: 2, column: 3, status: 'available' },
      { id: 'C-14', row: 2, column: 4, status: 'available' },
      { id: 'C-15', row: 2, column: 5, status: 'available' },
      { id: 'C-16', row: 2, column: 6, status: 'available' },
      { id: 'C-17', row: 2, column: 7, status: 'available' },
      { id: 'C-18', row: 2, column: 8, status: 'disabled' },
      { id: 'C-19', row: 2, column: 9, status: 'disabled' },
      { id: 'C-20', row: 2, column: 10, status: 'available' },
    ],
  },
];
